add todo ui
Dobubu/todo-list-react pull request #1
Opened 2021-04-28 15:14 UTC by Dobubu

2021-04-29 04:47 UTC, PolarBearAndrew requested changes

2021-04-29 04:47 UTC, PolarBearAndrew commented on src/App.js
> +`;
直接學你刪掉的那段 code 的寫法就好了，那是標準的 react template 的語言。react 本身就是有能理處理資料跟渲染的 framework，不需要在 react 裡面再調用一次 pug

2021-04-29 04:47 UTC, PolarBearAndrew commented on src/components/TodoForm.js
> +    </Form>
這個就是正確的寫法 👍

2021-04-29 06:13 UTC, Dobubu commented on src/App.js
> +`;
喔喔 所以這樣我改成 pug，可能會影響 react template 本身的其他問題摟

2021-04-29 06:13 UTC, Dobubu commented on src/components/TodoForm.js
> +    </Form>
ok

2021-05-01 16:49 UTC, PolarBearAndrew requested changes

2021-05-01 16:49 UTC, PolarBearAndrew commented on src/page/TodoApp.js
> +      <ListGroup>{todoItems}</ListGroup>
直接寫到 return 裡面可以讓 react 幫忙去處理 [A, B, C] 這個 arr 的每一個物件有沒有改變，會自動判斷有沒有觸發 rerender（重複渲染），如果你自己算完再放進去，那就必定會 rerender。

```suggestion
      <ListGroup>
        {['A', 'B', 'C'].map((o, i) => <TodoItem key={i} todo={o} />)}
      </ListGroup>
```

2021-05-01 16:49 UTC, PolarBearAndrew commented on src/styles/components/index.scss
> +@import "./todoItem";
**這隻PR先不處理，再發一個PR處理**
我在 Notion 上有建議你使用 style-components，避免在 react 裡面操作 classname，這樣會失去 react 的操作性。

舉例來說：
1. 沒辦法簡單的使用 react 裡面的參數數值當作 font-size
2. 切換樣式的時候只能依靠切換 class name

這個 PR merge 之後我寫一段給你看

2021-05-01 16:49 UTC, PolarBearAndrew commented on src/components/TodoItem.js
> +};
用了 Typescript 的好處就是可以這樣寫，之後 vscode 還會提醒我們 code 是否有寫對

```suggestion
interface TodoItemProps {
  todo: string;
}

const TodoItem: React.FunctionComponent<TodoItemProps> = ({ todo }) => {
  return (
    <ListGroup.Item>
      <Form className="d-flex align-items-center">
        <Form.Check className="mr-2" type="checkbox" />
        <Form.Label className="m-0">{todo}</Form.Label>
        <Button variant="danger" type="submit" className="ml-auto">
          Delete
        </Button>
      </Form>
    </ListGroup.Item>
  );
};
```

2021-05-01 16:50 UTC, PolarBearAndrew commented
這兩個調整完我們可以先 merge PR，然後我會跟你說可以做什麼優化

2021-05-02 08:18 UTC, Dobubu commented on src/page/TodoApp.js
> +      <ListGroup>{todoItems}</ListGroup>
喔好 那這個我先像你這樣寫

2021-05-03 13:22 UTC, Dobubu commented on src/styles/components/index.scss
> +@import "./todoItem";
ok

2021-05-03 13:35 UTC, Dobubu commented
參考的
https://github.com/typescript-cheatsheets/react#reacttypescript-cheatsheets
https://jkchao.github.io/typescript-book-chinese/jsx/reactJSX.html#%E5%87%BD%E6%95%B0%E5%BC%8F%E7%BB%84%E4%BB%B6

2021-05-03 15:18 UTC, PolarBearAndrew approved these changes

2021-05-03 15:18 UTC, PolarBearAndrew commented on tsconfig.json
> +}
非常棒，這組找得不錯

2021-05-03 15:18 UTC, PolarBearAndrew commented on src/components/TodoItem.tsx
> +export default TodoItem;
妳改成對的版本了，但是不是忘記使用了，舊的可以刪掉
這個之後發另一個 PR 改就好了，這次的 PR 沒問題了

2021-05-04 03:12 UTC, PolarBearAndrew commented on src/components/TodoItem.tsx
> +};
這個寫法也是可以的，但思維是完全不同的
我要求的你寫的 interface 是定義在 ```const TodoItem``` 上面，思考脈絡是 “這個變數應該長得像 func component” - > "你寫的東西必須符合這個規定"
而你的 code 的邏輯則是反過來的，"我不管 const TodoITem 是什麼變數" -> "這邊有個規則跟 func component 一樣的東西，你拿去用吧"

思考脈絡不同，結果也不同。在你的版本中如果你定義寫錯了，編輯器是不會通知你的。

2021-05-04 03:14 UTC, PolarBearAndrew commented on src/components/TodoItem.tsx
> +const TodoItem2: React.FunctionComponent<TodoItemProps2> = ({ todo }) => {
如果把這段刪掉之後還會有問題嗎？

```ts
type TodoItemProps = {
  todo: string;
};
```

2021-05-04 03:19 UTC, PolarBearAndrew commented on src/components/TodoItem.tsx
> +};
```suggestion
interface TodoItemProps {
  todo: string;
};
```

2021-05-04 03:19 UTC, PolarBearAndrew commented on src/components/TodoItem.tsx
> +const TodoItem2: React.FunctionComponent<TodoItemProps2> = ({ todo }) => {
先直接關掉就好了，在 typescript 裡面我們不需要對 props 做檢查，傳進去的參數本身就應該要是對的。javascript 賽有使用這條規的價值。

2021-05-04 03:19 UTC, PolarBearAndrew commented on src/components/TodoItem.tsx
> +};
99%  的情況都用 interface 就好了
`type` 屬於 typescript 比較早期的語法，少了一些功能

2021-05-04 08:06 UTC, Dobubu commented on src/components/TodoItem.tsx
> +};
喔喔 原來是這樣喔，好 感謝！

2021-05-04 08:06 UTC, Dobubu commented on src/components/TodoItem.tsx
> +const TodoItem2: React.FunctionComponent<TodoItemProps2> = ({ todo }) => {
好

2021-05-04 08:07 UTC, Dobubu commented on src/components/TodoItem.tsx
> +};
好

2021-05-04 08:08 UTC, merged