todo delete
Dobubu/todo-list-react pull request #5
Opened 2021-05-07 06:58 UTC by Dobubu

2021-05-07 08:40 UTC, PolarBearAndrew requested changes

2021-05-07 08:40 UTC, PolarBearAndrew commented on src/components/TodoItem.tsx
> +  removeTodo: (id: number) => void;
```suggestion
  removeTodoById: (id: number) => (e: React.SyntheticEvent) => void;
```

2021-05-07 08:40 UTC, PolarBearAndrew commented on src/components/TodoItem.tsx
> +  };
```suggestion
  const removeTodo = useCallback(() => removeTodoById(todo.id),  [todo.id])
```

2021-05-07 08:40 UTC, PolarBearAndrew commented on src/components/TodoItem.tsx
> +        <Button onClick={e => remove(e)} variant="danger" type="submit" className="ml-auto">
```suggestion
        <Button onClick={removeTodo} variant="danger" type="submit" className="ml-auto">
```

2021-05-07 08:40 UTC, PolarBearAndrew commented on src/components/TodoItem.tsx
> +  };
這層 callback 可以自行考慮要不要寫，取決於功能設計的時候 todo 會不會很常變動。
useCallback 避免這層元件重新計算的時候需要重掛 event listener 而已。

2021-05-07 08:40 UTC, PolarBearAndrew commented on src/page/TodoApp.tsx
> +    });
```suggestion
    setTodoItems((prev: ITodoItem[]) => prev.filter(o => o.id === id));
```

2021-05-07 09:55 UTC, Dobubu commented on src/page/TodoApp.tsx
> +    });
哇，沒想過這樣寫，簡單多了

2021-05-07 09:57 UTC, PolarBearAndrew commented on src/page/TodoApp.tsx
> +    });
我剛突然發現我自己寫錯了 `===`，已經改用 `!==`

2021-05-07 09:59 UTC, Dobubu commented on src/page/TodoApp.tsx
> +    });
嗯嗯 我發現了 👍

2021-05-07 13:16 UTC, Dobubu commented on src/components/TodoItem.tsx
> +  };
好 那我這邊先加，以會很常更新 todo 為前提

你可以順便幫我看看，我理解的渲染過程對不對麼？
結構 TodoApp -> TodoHeader、TodoForm、TodoItem

step 1：TodoForm 新增 todo，執行從 TodoApp props 過來的 addTodo() 
step 2：TodoApp 在 addTodo() 中執行 setTodoItems()，因為有更新到 state，所以 
  step 2.1：TodoApp 會重新渲染
  step 2.2：TodoApp 裡的 addTodo()，不會重新渲染，因為有使用 useCallback()
step 3：TodoHeader 會重新渲染，因為 TodoApp 有重新渲染
step 4：TodoForm 會重新渲染，因為 TodoApp 有重新渲染，裡面的 function 也都會被重新創建
step 5：TodoItem 會重新渲染，因為 TodoApp 有重新渲染，裡面的 removeTodo() 沒有用 useCallback()，所以也會被重新創建

---

這邊 TodoItem 的 removeTodo() 使用 useCallback() 的差別
（假設現在有 10 個 todo，然後增加一個 todo 進去）
沒加：之前這 10 個 todo 裡的 removeTodo() 都被重新創建
有加：之前這 10 個 todo 裡的 removeTodo() 都不會被重新創建

2021-05-07 13:24 UTC, Dobubu commented on src/components/TodoItem.tsx
> +  removeTodo: (id: number) => void;
不知道這邊為什麼需要加 (e: React.SyntheticEvent)

2021-05-09 15:29 UTC, PolarBearAndrew commented on src/components/TodoItem.tsx
> +  removeTodo: (id: number) => void;
這是一個 func 再包一個 event listener func

2021-05-09 15:37 UTC, PolarBearAndrew commented on src/components/TodoItem.tsx
> +  };
抱歉我上次沒看到，我以為我全部都回覆了，下次我超過一天沒回麻煩直接 line 我

1. 方向是對的，在 React 中每個 "重新渲染" 的時候都會檢查傳遞進去的參數跟之前一不一樣，不一樣的話才會重新渲染（裡面如果使用 context provider 就另幫別論）
2. 多數的變數比較之後，發現結果不變就不會被重新渲染。但在這邊 ```const remove = ....``` 的狀況是每次渲染 TodoItem 時，你都會創建一個新的 ```const remove```，而 fucntion 會用記憶體位置比較，所以每次都不相同，每次都重來。
3. 所以使用 useCallback 之後，React 會比較 useCallback 後面那個 array 有沒有不同，如果不同的話，才會重創一個，不然都會用同一個記憶體位的 function，自然後續就不會渲染
4. 後面你的舉例是正確的，而且因為每次 removeTodo 都不一樣，所以 event listener 都必須移除重掛。會消耗一定的資源。

2021-05-10 12:47 UTC, Dobubu commented on src/components/TodoItem.tsx
> +  };
好 我下次直接賴你

喔喔 好那這樣我有比較了解了，感謝幫忙

2021-05-10 12:58 UTC, Dobubu commented on src/components/TodoItem.tsx
> +  removeTodo: (id: number) => void;
喔喔 好的
其實我是想問，removeTodoById 這個 func，在 TodoApp 裡不是只有用到 id，為什麼裡面需要再加一個  (e: React.SyntheticEvent)，還是我漏了什麼麼？

2021-05-10 13:09 UTC, PolarBearAndrew commented on src/components/TodoItem.tsx
> +  removeTodo: (id: number) => void;
第一層的 func 把 id 包進去，回傳一個 event listener 而已
寫這個 e 只是為了表達是 event listener

2021-05-10 13:27 UTC, Dobubu commented on src/components/TodoItem.tsx
> +  removeTodo: (id: number) => void;
<img width="1440" alt="截圖 2021-05-10 下午9 24 37" src="https://user-images.githubusercontent.com/10227606/117666100-1813ca80-b1d6-11eb-9afb-97ef9cbbf9e3.png">
我有點障礙，他父層傳過來的 props removeTodoById func，不是只需要帶 id 麼？

2021-05-11 02:08 UTC, PolarBearAndrew commented on src/components/TodoItem.tsx
> +  removeTodo: (id: number) => void;
@Dobubu 
你父曾也需要改，右邊 30 行的地方要改成 return 一個 function
目的讓你再左邊不用再多包一層讓 function 變成 event listener

2021-05-11 12:56 UTC, merged